spring.application.name=rest
#spring.datasource.url=jdbc:postgresql://dpg-d97thn6trd3s739nra10-a.frankfurt-postgres.render.com/libros_418l
spring.datasource.url=jdbc:postgresql://dpg-d97thn6trd3s739nra10-a/libros_418l
server.port=8085
spring.datasource.username=postgre
spring.datasource.password=yPXhShbTSZBzW9EdNnHm4aw7iOxq4aWP
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update


#spring.datasource.url=jdbc:postgresql://localhost:5432/libros
#server.port=8085
#spring.datasource.username=postgres
#spring.datasource.password=cesar
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.com.zaxxer.hikari=DEBUG

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5